name: seller_mobile_app
description: "SnowWhite Group's app for getting products from a Seller"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.3
  introduction_screen: ^3.1.17
  shared_preferences: ^2.5.2
  iconsax: ^0.0.8
  phone_text_field: ^0.0.7
  get: ^4.7.2
  map_viewer_widget: ^0.0.6
  flutter_map: ^3.1.0
  latlong2: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/
    - assets/svg/


  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
